---
  - name: Load Interface Configuration
    copy: src=config/{{ansible_hostname}}/interfaces dest=/etc/network/
  
  - name: Apply Interface Configuration Delta
    shell: nohup bash -c 'sleep 2 && /sbin/ifreload -a > /tmp/ifreload.out 2>&1' &
    async: 1
    poll: 0
    changed_when: true
  
  - name: Wait 5 seconds for SSH port to Reopen and contain "OpenSSH" In The Connection String
    wait_for:
      port: 22
      host: '{{ ansible_host }}'
      search_regex: OpenSSH
      delay: 5
    connection: local
    become: false
