---
 - name: Load Interface Configuration
   copy: src=config/{{ansible_hostname}}/interfaces dest=/etc/network/

 - name: Restarts servers with their new configuration
   shell: sleep 1 && shutdown -r 0
   async: 1
   poll: 0
   ignore_errors: true

 - name: Wait for servers to reboot
   local_action: wait_for port=22 host="{{ inventory_hostname }}" search_regex=OpenSSH delay=10
